### ISSUE TITLE
感谢大佬！

### ISSUE THREAD

**Issue by Alecition** [wyh2001/suda-wifi#6]
原本自己照着网上其他学校的写了一个，结果用了一会就不好用了，发现它的IP会不断的改变，一搜发现了大佬写的，感谢！还有就是想问一下,和@为什么不能直接用网页上的%2C和%40？

**Comment by wyh2001** [comment]
不客气！不过你的问题我好像没有明白，能否再说的具体一些？我猜测大概是有关于python中requests的url编码问题，因为requests会默认对请求进行url编码，所以是不能直接用编码后的内容发送请求的，可以通过添加请求头解决。

**Comment by Alecition** [comment]
明白了，感谢。还有一个问题就是为什么网页中部分信息采用了url编码，部分没采用，比如这里面只有,和@采用了编码显示

**Comment by wyh2001** [comment]
url编码有特定的规则，概而论之，英文字母以及特定符号不需要编码，但不同情况下也会有差异。建议你可以使用搜索引擎去查一下相关的资料。

**Comment by Alecition** [comment]
好的，谢谢大佬！我有时间会去学习一下的

**Comment by wyh2001** [comment]
🤝
